<script setup lang="ts">
import { accessibilityPackages, buildPackages, carePlan } from '~/content/packages'
import { site } from '~/content/site'

const selectedInterest = ref('New Website')
useHead({ title: site.title, meta: [{ name: 'description', content: site.description }], link: [{ rel: 'canonical', href: 'https://keithpotter.net' }] })
</script>

<template>
  <div class="site-page">
    <a href="#main-content" class="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:bg-white focus:px-4 focus:py-2 focus:text-black">Skip to content</a>
    <SiteHeader />
    <main id="main-content">
      <section class="reference-hero"><div class="section-shell reference-hero__grid"><div class="reference-hero__copy"><h1>Hi, I’m Keith.<br>I build <em>websites.</em></h1><p class="intro-copy">I have been building websites for a long time. I’m not going to bore you with all the details—unless you’re into that sort of thing, and in that case, let’s get nerdy.</p></div><figure class="hero-photo" aria-label="Portrait of Keith Potter"><img :src="site.portrait.src" :alt="site.portrait.alt" loading="eager"></figure></div></section>

      <section id="packages" class="section-shell section-space" aria-labelledby="packages-title"><p class="pink-eyebrow">Packages</p><h2 id="packages-title" class="section-title">You’re here. I’m here. You need a website.</h2><p class="section-lede">Let’s not overthink this.</p><div class="package-grid"><article v-for="pkg in buildPackages" :key="pkg.name" class="price-card" :class="{ 'price-card--featured': pkg.featured }"><span v-if="pkg.featured" class="popular-tag">Most popular</span><p class="card-kicker">{{ pkg.name }}</p><p class="price-detail">{{ pkg.detail }}</p><h3>{{ pkg.price }}</h3><p class="card-intro">{{ pkg.description }}</p><ul><li v-for="feature in pkg.features" :key="feature"><span>✓</span>{{ feature }}</li></ul><a href="#contact" class="outline-button card-action" @click="selectedInterest = pkg.name">Get Started <span aria-hidden="true">→</span></a></article></div></section>

      <section class="support-section" aria-labelledby="support-title"><div class="section-shell support-grid"><figure class="support-visual"><img src="/images/support-workspace.png" alt="Laptop and coffee mug on a dark, magenta-lit workspace"></figure><div class="support-copy"><p class="pink-eyebrow">Ongoing support</p><h2 id="support-title" class="section-title">Now that we got that out of the way…</h2><p class="body-copy">This is what I really want to build you! One monthly plan, less to think about.</p><h3>Starting at {{ carePlan.price }}</h3><ul class="check-list"><li v-for="item in carePlan.items" :key="item">{{ item }}</li></ul><a href="#contact" class="outline-button pink-outline" @click="selectedInterest = 'Website Care'">Let’s Make It Happen <span aria-hidden="true">→</span></a></div></div></section>

      <section class="section-shell profile-package" aria-labelledby="profile-package-title"><div><p class="pink-eyebrow">Google Business Profile</p><h2 id="profile-package-title" class="section-title">Managing your Google Business Profile.</h2><p class="body-copy">Keep one of your most important local-search tools accurate, active, and working alongside your website.</p><div class="profile-package-details"><h3>Starting at $99/month</h3><ul class="check-list"><li>Profile audit, cleanup, and accuracy checks</li><li>Business details, hours, services, and categories kept current</li><li>Website, booking, and contact links reviewed and maintained</li><li>Regular posts, photos, and business updates</li><li>Review-monitoring guidance and customer response support</li><li>Local-search visibility checks and practical recommendations</li></ul><a href="#contact" class="outline-button pink-outline" @click="selectedInterest = 'Google Business Profile'">Talk About Your Profile <span aria-hidden="true">→</span></a></div></div><figure class="profile-map"><img src="/images/google-business-map.png" alt="Illustrated local business map with colorful location pins"></figure></section>

      <section id="accessibility" class="section-shell section-space" aria-labelledby="accessibility-title"><p class="pink-eyebrow">Accessibility</p><h2 id="accessibility-title" class="section-title accessibility-title">Our A11Y friends should be able to use your website too.</h2><p class="section-lede">Because people should be able to use your website without having to fight it first.</p><div class="access-grid"><div class="access-cards"><article v-for="item in accessibilityPackages" :key="item.title" class="access-card"><h3>{{ item.title }}</h3><p class="access-price">{{ item.price }}</p><p class="body-copy">{{ item.description }}</p><a href="#contact" class="outline-button pink-outline" @click="selectedInterest = item.title">{{ item.title === 'Accessibility Audit' ? 'Request an Audit' : 'Let’s Fix It' }} <span aria-hidden="true">→</span></a></article></div></div></section>

      <section id="contact" class="section-shell contact-section" aria-labelledby="contact-title"><div class="contact-intro"><p class="pink-eyebrow">Start a project</p><h2 id="contact-title">Let’s talk about<br>your business.</h2><p>Tell me what you’re working on and I’ll get back to you personally.</p><a :href="`mailto:${site.email}`">{{ site.email }}</a></div><div class="contact-form-wrap"><ContactForm :interest="selectedInterest" /></div></section>
    </main>
    <footer class="site-footer"><div class="section-shell"><SiteLogo /><p>Websites. Accessibility. Results.</p><nav aria-label="Footer navigation"><a href="#main-content">Home</a><a href="#packages">Packages</a><a href="#accessibility">Accessibility</a><a href="#contact">Contact</a></nav></div></footer>
  </div>
</template>
