<script setup lang="ts">
import { credentials, problems, services, site } from '~/content/site'
import { accessibilityPackages, buildPackages, carePlan } from '~/content/packages'
const selectedInterest = ref('New Website')
useHead({ title: site.title, meta: [{ name: 'description', content: site.description }], link: [{ rel: 'canonical', href: 'https://keithpotter.net' }] })
</script>

<template>
  <div>
    <a href="#main-content" class="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:bg-paper focus:px-4 focus:py-2 focus:text-ink">Skip to content</a>
    <SiteHeader />
    <main id="main-content">
      <section class="relative overflow-hidden border-b border-white/10">
        <div class="pointer-events-none absolute inset-0 grid-glow opacity-30" /><div class="pointer-events-none absolute -right-40 top-4 h-96 w-96 rounded-full bg-violet/20 blur-[130px]" />
        <div class="section-shell relative grid gap-12 py-16 sm:py-20 lg:grid-cols-[1.12fr_.88fr] lg:items-center lg:py-24">
          <div><p class="eyebrow">Independent web developer · 20+ years</p><h1 class="mt-5 max-w-3xl text-5xl font-semibold leading-[.95] tracking-[-.075em] sm:text-7xl lg:text-8xl">I build websites that <span class="gradient-text">work for your business.</span></h1><p class="mt-7 max-w-2xl text-lg leading-8 text-muted sm:text-xl">I’m Keith Potter, an independent web developer with more than 20 years of experience. I build fast, accessible websites that help small businesses look professional, get found, and turn visitors into customers.</p><div class="mt-9 flex flex-wrap gap-4"><a href="#contact" class="rounded-full bg-paper px-6 py-3 font-semibold text-ink transition hover:bg-cyan">Start a Project <span aria-hidden="true">→</span></a><a href="#services" class="rounded-full border border-white/20 px-6 py-3 font-semibold transition hover:border-cyan hover:text-cyan">See What I Do</a></div></div>
          <figure class="mx-auto w-full max-w-sm"><div class="portrait-backdrop relative aspect-[4/5] overflow-hidden border border-white/15"><div class="absolute inset-x-0 top-0 z-10 h-1 gradient-line" /><div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-ink/35 to-transparent" aria-hidden="true" /><img :src="site.portrait.src" :alt="site.portrait.alt" class="relative z-10 h-full w-full object-cover" loading="eager" /></div></figure>
        </div>
      </section>
      <section aria-label="Credentials" class="border-b border-white/10 bg-surface"><div class="section-shell grid grid-cols-2 divide-x divide-y divide-white/10 sm:grid-cols-5 sm:divide-y-0"><div v-for="credential in credentials" :key="credential.value" class="p-5 sm:p-6"><strong class="block text-lg">{{ credential.value }}</strong><span class="mt-1 block text-sm text-muted">{{ credential.label }}</span></div></div></section>
      <section class="section-shell py-20 sm:py-28" aria-labelledby="problems-heading"><div class="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">A familiar story</p><h2 id="problems-heading" class="mt-4 text-4xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl">Your website should be working as hard as your business.</h2></div><div class="grid"><article v-for="problem in problems" :key="problem.number" class="grid gap-4 border-t border-white/10 py-6 sm:grid-cols-[4rem_1fr]"><span class="font-mono text-sm text-cyan">{{ problem.number }}</span><div><h3 class="text-xl font-semibold">{{ problem.title }}</h3><p class="mt-2 leading-7 text-muted">{{ problem.description }}</p></div></article></div></div></section>
      <section id="why-me" class="border-y border-white/10 bg-paper py-20 text-ink sm:py-28" aria-labelledby="why-heading"><div class="section-shell grid gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p class="eyebrow !text-ink/60">Why me</p><h2 id="why-heading" class="mt-5 text-5xl font-semibold leading-[.94] tracking-[-.07em] sm:text-7xl">20+ years of experience.<br><span class="text-violet">One person</span> accountable for the result.</h2><p class="mt-8 max-w-xl text-lg leading-8 text-ink/70">Most of my professional work happens behind the scenes. I’ve spent years building and maintaining enterprise websites as part of professional development teams. The standards and practices I’ve learned there go into every site I build.</p><p class="mt-5 text-sm text-ink/60">Some professional client work is confidential and cannot be displayed publicly.</p></div><div><p class="border-l-2 border-fuchsia-500 pl-5 text-2xl font-medium leading-9">No agency. No handoffs. You work directly with me.</p><ol class="mt-10 grid gap-6"><li v-for="item in [['01','Experience','Building websites professionally since 2006.'],['02','Enterprise standards','Accessibility, reliability, performance, and maintainability matter.'],['03','Built right','Responsive design, SEO, and modern web standards are part of the process.'],['04','No lock-in','Launch it and own it—or keep me in your corner.']]" :key="item[0]" class="grid grid-cols-[3rem_1fr] gap-3"><span class="font-mono text-sm text-violet">{{ item[0] }}</span><div><h3 class="font-semibold">{{ item[1] }}</h3><p class="mt-1 text-sm leading-6 text-ink/65">{{ item[2] }}</p></div></li></ol></div></div></section>
      <NeedsSelector @select="selectedInterest = $event" />
      <section id="services" class="section-shell py-20 sm:py-28" aria-labelledby="services-heading"><div class="max-w-2xl"><p class="eyebrow">What I do</p><h2 id="services-heading" class="mt-4 text-4xl font-semibold tracking-[-.06em] sm:text-6xl">The web work that helps your business show up well.</h2></div><div class="mt-12 grid divide-y divide-white/10 border-t border-white/10"><article v-for="service in services" :key="service.number" class="grid gap-4 py-7 sm:grid-cols-[5rem_1fr_1fr]"><span class="font-mono text-sm text-cyan">{{ service.number }}</span><h3 class="text-xl font-semibold">{{ service.title }}</h3><p class="leading-7 text-muted">{{ service.description }}</p></article></div></section>
      <section id="pricing" class="border-y border-white/10 bg-surface py-20 sm:py-28" aria-labelledby="pricing-heading"><div class="section-shell"><p class="eyebrow">Project pricing</p><h2 id="pricing-heading" class="mt-4 text-4xl font-semibold tracking-[-.06em] sm:text-6xl">Clear starting points. Built around your business.</h2><div class="mt-12 grid gap-px overflow-hidden border border-white/10 bg-white/10 lg:grid-cols-3"><article v-for="pkg in buildPackages" :key="pkg.name" class="relative bg-surface p-7 sm:p-8" :class="pkg.featured ? 'bg-elevated' : ''"><span v-if="pkg.featured" class="absolute right-5 top-5 rounded-full bg-cyan px-3 py-1 text-xs font-semibold text-ink">Most Popular</span><h3 class="text-2xl font-semibold">{{ pkg.name }}</h3><p class="mt-5 text-3xl font-semibold tracking-[-.05em]">{{ pkg.price }}</p><p class="mt-2 text-sm text-cyan">{{ pkg.detail }}</p><p class="mt-5 leading-7 text-muted">{{ pkg.description }}</p><ul class="mt-7 grid gap-3 text-sm text-paper/85"><li v-for="feature in pkg.features" :key="feature" class="flex gap-3"><span class="text-cyan">+</span>{{ feature }}</li></ul><a href="#contact" class="mt-9 inline-flex font-semibold text-cyan hover:text-paper">Let’s Talk <span class="ml-2">→</span></a></article></div></div></section>
      <section class="section-shell py-20 sm:py-28"><div class="grid gap-12 lg:grid-cols-2"><div><p class="eyebrow">Your ownership</p><h2 class="mt-4 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">It’s your website.</h2><p class="mt-5 max-w-xl text-lg leading-8 text-muted">You’re paying for a website, not renting one forever. When the project is completed and paid for, the finished site belongs to you according to the project agreement. You can hand over the keys—or keep me involved for ongoing care.</p></div><div class="border-l border-cyan/60 pl-7"><p class="eyebrow">Optional ongoing care</p><h3 class="mt-4 text-3xl font-semibold">{{ carePlan.title }} <span class="text-cyan">{{ carePlan.price }}</span></h3><p class="mt-4 text-muted">You run your business. I’ll handle the website.</p><ul class="mt-5 grid gap-3 text-sm"><li v-for="item in carePlan.items" :key="item" class="flex gap-3"><span class="text-cyan">✦</span>{{ item }}</li></ul><p class="mt-5 text-xs leading-5 text-muted">{{ carePlan.note }}</p></div></div></section>
      <section class="border-y border-white/10 bg-[#10171d] py-20 sm:py-28" aria-labelledby="access-heading"><div class="section-shell"><div class="max-w-3xl"><p class="eyebrow">Accessibility</p><h2 id="access-heading" class="mt-4 text-5xl font-semibold leading-[.95] tracking-[-.065em] sm:text-7xl">Accessibility isn’t an add-on.<br><span class="gradient-text">It’s part of how I build.</span></h2><p class="mt-7 text-lg leading-8 text-muted">Inclusive websites are better for people and better for business. That means usable keyboards and forms, semantic structure, screen-reader compatibility, strong contrast, visible focus states, and thoughtful WCAG-informed engineering.</p></div><div class="mt-12 grid gap-5 md:grid-cols-2"><article v-for="item in accessibilityPackages" :key="item.title" class="border border-white/12 bg-ink/60 p-7"><p class="text-sm text-cyan">{{ item.price }}</p><h3 class="mt-3 text-2xl font-semibold">{{ item.title }}</h3><p class="mt-4 leading-7 text-muted">{{ item.description }}</p><a href="#contact" class="mt-7 inline-flex font-semibold text-cyan hover:text-paper" @click="selectedInterest = item.title">Talk to Me About Accessibility →</a></article></div></div></section>
      <section class="section-shell py-16"><div class="flex flex-col justify-between gap-6 border border-white/10 p-7 sm:flex-row sm:items-center"><div><p class="eyebrow">Drupal projects</p><h2 class="mt-2 text-2xl font-semibold">Looking for Drupal development?</h2><p class="mt-2 max-w-2xl text-muted">My independent work focuses on small-business websites. For Drupal development, migrations, upgrades, and enterprise projects, I recommend the team at Y3TI.</p></div><a class="shrink-0 font-semibold text-cyan hover:text-paper" href="https://y3ti.com/?utm_source=keithpotter.net&utm_medium=referral&utm_campaign=drupal-referral" target="_blank" rel="noopener noreferrer">Talk to Y3TI <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a></div></section>
      <section id="contact" class="border-t border-white/10 bg-surface py-20 sm:py-28" aria-labelledby="contact-heading"><div class="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">Start a project</p><h2 id="contact-heading" class="mt-4 text-5xl font-semibold leading-[.95] tracking-[-.07em] sm:text-7xl">Let’s talk about your business.</h2><p class="mt-6 max-w-md text-lg leading-8 text-muted">Tell me what you’re working on and I’ll get back to you personally.</p><a class="mt-8 inline-block text-cyan hover:text-paper" :href="`mailto:${site.email}`">{{ site.email }}</a></div><ContactForm :interest="selectedInterest" /></div></section>
    </main>
    <footer class="border-t border-white/10 py-10"><div class="section-shell flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><SiteLogo /><p class="mt-3 text-sm text-muted">Keith Potter — Web Developer</p></div><div class="flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted"><NuxtLink v-for="link in [...[{label:'Privacy',href:'/privacy'}], ...[]]" :key="link.href" :to="link.href" class="hover:text-paper">{{ link.label }}</NuxtLink><span>© {{ new Date().getFullYear() }} Keith Potter</span></div></div></footer>
  </div>
</template>
